trooper/address_book/urls.py
from django.urls import path

from trooper.address_book.views import (
    AddressCreateView,
    AddressDeleteView,
    AddressDetailView,
    AddressListView,
    AddressUpdateView,
)

app_name = "address_book"
urlpatterns = [
    path("<slug:username>/address/", AddressListView.as_view(), name="address_list"),
    path(
        "<slug:username>/address/add/",
        AddressCreateView.as_view(),
        name="address_create",
    ),
    path(
        "<slug:username>/address/<int:pk>/",
        AddressDetailView.as_view(),
        name="address_detail",
    ),
    path(
        "<slug:username>/address/<int:pk>/edit",
        AddressUpdateView.as_view(),
        name="address_update",
    ),
    path(
        "<slug:username>/address/<int:pk>/delete/",
        AddressDeleteView.as_view(),
        name="address_delete",
    ),
]

trooper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path
from django.views import defaults


def ping(*args):
    return JsonResponse({"ping": "pong"})


urlpatterns = [
    # Ping test endpoint
    path("ping/", ping, name="ping"),
    # Django admin
    path("admindocs/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # Trooper
    path("", include("trooper.members.auth.urls")),
    path("address_book/", include("trooper.address_book.urls")),
    path("calendars/", include("trooper.calendars.urls")),
    path("members/", include("trooper.members.urls")),
    path("", include("trooper.website.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [
        # Debug error webpages
        path(
            "400/", defaults.bad_request, kwargs={"exception": Exception("Bad Request")}
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", defaults.server_error),
    ] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        try:
            import debug_toolbar
        except ImportError:
            pass
        else:
            urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

trooper/address_book/models.py
from django.db import models
from django.db.models.functions import Lower
from django.utils.functional import cached_property
from django.utils.html import format_html
from django.utils.translation import gettext as _

from localflavor.us.models import USStateField, USZipCodeField
from phonenumber_field.modelfields import PhoneNumberField


class Address(models.Model):
    street = models.CharField(_("street"), max_length=150)
    street2 = models.CharField(
        _("street 2"),
        max_length=150,
        blank=True,
        help_text=_("e.g. Apartment, Suite, Box Number"),
    )
    city = models.CharField(_("city"), max_length=50)
    state = USStateField(_("state"))
    zip_code = USZipCodeField(_("ZIP code"))

    class Meta:
        verbose_name = _("Address")
        verbose_name_plural = _("Addresses")

    def __str__(self):
        return self.as_single_line

    @cached_property
    def as_single_line(self):
        fields = [self.street, self.street2, self.city, self.state, self.zip_code]
        return ", ".join(field.strip() for field in fields if field)

    @cached_property
    def as_multiline(self):
        if self.street2:
            return format_html(
                "{}<br> {}<br> {}, {} {}",
                self.street,
                self.street2,
                self.city,
                self.state,
                self.zip_code,
            )
        else:
            return format_html(
                "{}<br> {}, {} {}",
                self.street,
                self.city,
                self.state,
                self.zip_code,
            )


class EmailAddressManager(models.Manager):
    def get_by_natural_key(self, address):
        return self.get(address__iexact=address)


class EmailAddress(models.Model):
    address = models.EmailField(_("email address"), unique=True)

    objects = EmailAddressManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(Lower("address"), name="unique_email_address"),
        ]
        verbose_name = _("Email Address")
        verbose_name_plural = _("Email Addresses")

    def __str__(self):
        return self.address

    def natural_key(self):
        return (self.address.lower(),)


class PhoneNumberManager(models.Manager):
    def get_by_natural_key(self, number):
        return self.get(number=number)


class PhoneNumber(models.Model):
    number = PhoneNumberField(_("phone number"), unique=True)

    objects = PhoneNumberManager()

    class Meta:
        verbose_name = _("Phone Number")
        verbose_name_plural = _("Phone Numbers")

    def __str__(self):
        return self.number.as_national

    def natural_key(self):
        return (self.number.as_e164,)


class Location(models.Model):
    name = models.CharField(_("name"), max_length=100)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)

    class Meta:
        ordering = ("name",)
        verbose_name = _("Location")
        verbose_name_plural = _("Locations")

    def __str__(self):
        return self.name

trooper/address_book/forms.py
from django import forms

from trooper.address_book.models import Address


class AddressForm(forms.ModelForm):
    error_css_class = "is-invalid"

    class Meta:
        model = Address
        fields = (
            "street",
            "street2",
            "city",
            "state",
            "zip_code",
        )
        widgets = {
            "street": forms.TextInput(
                attrs={"autocomplete": "address-line1", "class": "form-control"}
            ),
            "street2": forms.TextInput(
                attrs={"autocomplete": "address-line2", "class": "form-control"}
            ),
            "city": forms.TextInput(
                attrs={"autocomplete": "address-level2", "class": "form-control"}
            ),
            "state": forms.Select(
                attrs={"autocomplete": "address-level1", "class": "form-select"}
            ),
            "zip_code": forms.TextInput(
                attrs={"autocomplete": "postal-code", "class": "form-control"}
            ),
        }


class EmailForm(forms.ModelForm):
    error_css_class = "is-invalid"

    class Meta:
        fields = ("address",)
        widgets = {
            "address": forms.EmailInput(
                attrs={"autocomplete": "email", "class": "form-control"}
            )
        }


class PhoneForm(forms.ModelForm):
    error_css_class = "is-invalid"

    class Meta:
        fields = ("number",)
        widgets = {
            "number": forms.TextInput(
                attrs={"autocomplete": "tel", "class": "form-control"}
            )
        }

trooper/address_book/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)
from django.views.generic.detail import SingleObjectMixin

from django_htmx.http import HttpResponseClientRedirect

from trooper.address_book.forms import AddressForm
from trooper.address_book.models import Address
from trooper.members.models import Member


class MemberMixin(SingleObjectMixin):
    def get_context_data(self, **kwargs):
        member = self.get_member()
        context = super().get_context_data(**kwargs)
        context["member"] = member
        context["members_are_related"] = member.is_related_to(self.request.user)
        return context

    def get_member(self):
        return get_object_or_404(Member, username=self.kwargs.get("username"))


class AddressListView(LoginRequiredMixin, ListView):
    model = Address

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context["member"] = self.member
        context["members_are_related"] = self.member.is_related_to(self.request.user)
        return context

    def get_queryset(self):
        username = self.kwargs.get("username")
        qs = super().get_queryset()
        qs = qs.filter(member__username=username)

        if not self.member.is_related_to(self.request.user):
            qs = qs.published()
        return qs

    def get_template_names(self):
        template_names = super().get_template_names()
        if self.request.htmx:
            for i, template_name in enumerate(template_names):
                parts = template_name.split("/")
                parts.insert(len(parts) - 1, "partials")
                template_names[i] = "/".join(parts)
        return template_names

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.member = get_object_or_404(Member, username=self.kwargs.get("username"))


class AddressCreateView(
    LoginRequiredMixin, MemberMixin, SuccessMessageMixin, CreateView
):
    model = Address
    form_class = AddressForm
    template_name = "address_book/address_form.html"

    def get_success_url(self):
        if self.request.htmx:
            return reverse(
                "address_book:address_list",
                kwargs={"username": self.kwargs.get("username")},
            )
        return self.get_member().get_absolute_url()

    def get_template_names(self):
        template_names = super().get_template_names()
        if self.request.htmx:
            for i, template_name in enumerate(template_names):
                parts = template_name.split("/")
                parts.insert(len(parts) - 1, "partials")
                template_names[i] = "/".join(parts)
        return template_names

    def form_valid(self, form):
        with transaction.atomic():
            address = form.save(commit=False)
            address.content_object = self.get_member()
        return super().form_valid(form)


class AddressDetailView(LoginRequiredMixin, MemberMixin, DetailView):
    model = Address
    template_name = "address_book/address_detail.html"


class AddressUpdateView(
    LoginRequiredMixin, MemberMixin, SuccessMessageMixin, UpdateView
):
    model = Address
    form_class = AddressForm
    success_message = _("Address has been updated.")
    template_name = "address_book/address_form.html"

    def get_success_url(self):
        if self.request.htmx:
            return reverse(
                "address_book:address_list",
                kwargs={"username": self.kwargs.get("username")},
            )
        return self.get_member().get_absolute_url()

    def get_template_names(self):
        template_names = super().get_template_names()
        if self.request.htmx:
            for i, template_name in enumerate(template_names):
                parts = template_name.split("/")
                parts.insert(len(parts) - 1, "partials")
                template_names[i] = "/".join(parts)
        return template_names

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.content_object = self.get_member()
        return super().form_valid(form)


class AddressDeleteView(LoginRequiredMixin, MemberMixin, DeleteView):
    model = Address
    template_name = "address_book/address_delete.html"

    def get_success_url(self):
        return self.get_member().get_absolute_url()

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_message = _("Address has been removed.")
        messages.warning(request, success_message, "danger")
        success_url = self.get_success_url()
        self.object.delete()

        if self.request.htmx:
            return HttpResponseClientRedirect(success_url)

        return HttpResponseRedirect(success_url)


# Create your views here.
def address_form_view(request, username=None, pk=None):
    member = None
    address = None

    if username and pk:
        member = get_object_or_404(Member, username=username)
        try:
            address = member.addresses.get(pk=pk)
        except Address.DoesNotExist as e:
            raise Http404 from e

    form = AddressForm(request.POST or None, instance=address)
    context = {"address": address, "form": form, "member": member}

    if address:
        context["members_are_related"] = member.is_related_to(request.user)

    template_name = "address_book/address_form.html"
    if request.htmx:
        template_name = "address_book/partials/address_form.html"

    if form.is_valid():
        with transaction.atomic():
            address = form.save(commit=False)
            if not address.content_object:
                user = request.user
                address.content_object = user
                address.save()
            if request.htmx:
                template_name = "address_book/partials/address_list_entry.html"

    return render(request, template_name, context)


def address_delete_view(request, pk=None):
    try:
        obj = Address.objects.get(pk=pk)
    except Address.DoesNotExist:
        obj = None
    if not obj:
        return HttpResponse("Not Found") if request.htmx else Http404

    if request.method == "DELETE":
        # TODO: Stay on the same page
        success_url = request.user.get_absolute_url()
        obj.delete()
        if request.htmx:
            headers = {"HX-Redirect": success_url}
            return HttpResponse("Success", headers=headers)
        return redirect(success_url)

    context = {"obj": obj, "address": obj}
    return render(request, "address_book/address_delete.html", context)

trooper/address_book/templates/address_book/partials/address_delete_form.html
{% load i18n %}

<form action="." method="post">
  {% csrf_token %}
  <button class="btn btn-danger">{% translate 'Delete' %}</button>
  <a class="btn btn-outline-primary" href="">{% translate 'Cancel' %}</a>
</form>

trooper/address_book/templates/address_book/partials/address_form.html
{% load i18n %}
{% if address.pk %}
  {% url 'address_book:address_update' member.username address.pk as form_url %}
{% else %}
  {% url 'address_book:address_create' member.username as form_url %}
{% endif %}
<form action="{{ form_url }}" method="post" hx-post="{{ form_url }}" hx-swap="outerHTML">
  {{ form.as_p }}
  {% csrf_token %}
  <button class="btn btn-outline-primary btn-sm" type="submit">
    {% if address.pk %}
      {% translate 'update' %}
    {% else %}
      {% translate 'add' %}
    {% endif %}
  </button>
  <a class="btn btn-outline-danger btn-sm" href="{{ member.get_absolute_url }}">cancel</a>
</form>

trooper/address_book/templates/address_book/partials/address_list.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
{% if members_are_related or addresses|length %}
  <div class="d-flex justify-content-between align-items-center" id="address-list-container" hx-swap-oob="true">
    <h3 class="card-title fs-6">
      {% blocktrans count counter=addresses|length %}
        Address
      {% plural %}
        Addresses
      {% endblocktrans %}
    </h3>
    {% if members_are_related %}
      <button class="btn btn-link btn-sm"
              hx-get="{% url 'address_book:address_create' member.username %}"
              hx-target="#{{ member.username }}-address-form"
              aria-label="{% translate 'add' %}">
        <svg class="bi">
          <use href="{{ icons }}#plus-circle-fill"></use>
        </svg>
      </button>
    {% endif %}
  </div>
  <ul class="list-group list-group-flush list-icons mb-4" id="{{ member.username }}-address-list">
    {% for address in address_list %}
      <li class="list-group-item {% if not address.is_published %}list-group-item-light{% endif %} d-flex justify-content-between align-items-start"
          id="address-{{ address.pk }}">
        {% include 'address_book/partials/address_list_entry.html' %}
      </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between align-items-start"
        id="{{ member.username }}-address-form"></li>
  </ul>
{% endif %}

trooper/address_book/templates/address_book/partials/address_list_entry.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
<div class="me-auto">
  <span class="list-icons-icon">
    {% if address.label == address.Label.HOME %}
      <svg class="bi">
        <use href="{{ icons }}#house"></use>
      </svg>
    {% elif address.label == address.Label.PO_BOX %}
      <svg class="bi">
        <use href="{{ icons }}#mailbox"></use>
      </svg>
    {% elif address.label == address.Label.WORK %}
      <svg class="bi">
        <use href="{{ icons }}#building"></use>
      </svg>
    {% else %}
      <svg class="bi">
        <use href="{{ icons }}#geo"></use>
      </svg>
    {% endif %}
    {% if not address.is_published %}
      <svg class="bi">
        <use href="{{ icons }}#eye-slash"></use>
      </svg>
    {% endif %}
  </span>
  {{ address.as_multiline }}
</div>
{% if members_are_related %}
  <div class="btn-group" role="group" aria-label="{% translate 'Address editing buttons' %}">
    <a class="btn btn-outline-secondary btn-sm"
       {% url 'address_book:address_update' member.username address.pk as address_update %}
       href="{{ address_update }}"
       hx-trigger="click"
       hx-get="{{ address_update }}"
       hx-target="#address-{{ address.pk }}"
       aria-label="{% translate 'edit' %}">
      <svg class="bi">
        <use href="{{ icons }}#pencil-square"></use>
      </svg>
    </a>
    <a class="btn btn-outline-danger btn-sm"
       {% url 'address_book:address_delete' member.username address.pk as address_delete %}
       href="{{ address_delete }}"
       hx-delete="{{ address_delete }}"
       hx-confirm="Are you sure you want to delete {{ address.as_single_line }}?"
       hx-target="#address-{{ address.pk }}"
       hx-swap="outerHTML"
       aria-label="{% translate 'delete' %}">
      <svg class="bi">
        <use href="{{ icons }}#trash"></use>
      </svg>
    </a>
  </div>
{% endif %}

trooper/address_book/templates/address_book/partials/email_address_list.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
{% if members_are_related or email_addresses|length %}
  <div class="d-flex justify-content-between align-items-center">
    <h3 class="card-title fs-6">
      {% blocktrans count counter=email_addresses|length %}
        Email Address
      {% plural %}
        Email Addresses
      {% endblocktrans %}
    </h3>
    {% if members_are_related %}
      <button class="btn btn-link btn-sm" aria-label="{% translate 'add' %}">
        <svg class="bi">
          <use href="{{ icons }}#plus-circle-fill"></use>
        </svg>
      </button>
    {% endif %}
  </div>
  <ul class="list-group list-group-flush list-icons mb-4" id="{{ member.username }}.email-address-list">
    {% for email in email_addresses %}
      <li class="list-group-item {% if not email.is_published %}list-group-item-light{% endif %} d-flex justify-content-between align-items-start"
          id="email-{{ email.pk }}">
        {% include 'address_book/partials/email_address_list_entry.html' %}
      </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between align-items-start" id="{{ member.username }}-email-address-form"></li>
  </ul>
{% endif %}

trooper/address_book/templates/address_book/partials/email_address_list_entry.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
<div class="me-auto">
  <span class="list-icons-icon">
    {% if email.label == email.Label.HOME %}
      <svg class="bi">
        <use href="{{ icons }}#house"></use>
      </svg>
    {% elif email.label == email.Label.WORK %}
      <svg class="bi">
        <use href="{{ icons }}#briefcase"></use>
      </svg>
    {% else %}
      <svg class="bi">
        <use href="{{ icons }}#envelope"></use>
      </svg>
    {% endif %}
    {% if not email.is_published %}
      <svg class="bi">
        <use href="{{ icons }}#eye-slash"></use>
      </svg>
    {% endif %}
  </span>
  {% if request.resolver_match.url_name == 'detail' %}
    <a href="mailto:{{ email.address }}?subject=%5B{{ website.name|urlencode }}%5D%20"
       class="card-link text-decoration-none">
  {% endif %}
  {{ email }}
  {% if request.resolver_match.url_name == 'detail' %}
    </a>
  {% endif %}
</div>
{% if members_are_related %}
  <div class="btn-group" role="group" aria-label="{% translate 'Address editing buttons' %}">
    <button class="btn btn-outline-secondary btn-sm"
            hx-trigger="click"
            hx-get=""
            hx-target="#email-{{ email.pk }}"
            aria-label="{% translate 'edit' %}">
      <svg class="bi">
        <use href="{{ icons }}#pencil-square"></use>
      </svg>
    </button>
    <a class="btn btn-outline-danger btn-sm"
       href=""
       hx-delete=""
       hx-confirm=""
       hx-target="#email-{{ email.pk }}"
       hx-swap="outerHTML"
       aria-label="{% translate 'delete' %}">
      <svg class="bi">
        <use href="{{ icons }}#trash"></use>
      </svg>
    </a>
  </div>
{% endif %}

trooper/address_book/templates/address_book/partials/phone_number_list.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
{% if members_are_related or phone_numbers|length %}
  <div class="d-flex justify-content-between align-items-center">
    <h3 class="card-title fs-6">
      {% blocktrans count counter=phone_numbers|length %}
        Phone Number
      {% plural %}
        Phone Numbers
      {% endblocktrans %}
    </h3>
    {% if members_are_related %}
      <button class="btn btn-link btn-sm" aria-label="{% translate 'add' %}">
        <svg class="bi">
          <use href="{{ icons }}#plus-circle-fill"></use>
        </svg>
      </button>
    {% endif %}
  </div>
  <ul class="list-group list-group-flush list-icons mb-4" id="{{ member.username }}-phone-number-list">
    {% for phone in phone_numbers %}
      <li class="list-group-item {% if not phone.is_published %}list-group-item-light{% endif %} d-flex justify-content-between align-items-start"
          id="phone-{{ phone.pk }}">
        {% include 'address_book/partials/phone_number_list_entry.html' %}
      </li>
    {% endfor %}
    <li class="list-group-item d-flex justify-content-between align-items-start" id="{{ member.username }}-phone-number-form"></li>

  </ul>
{% endif %}

trooper/address_book/templates/address_book/partials/phone_number_list_entry.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
<div class="me-auto">
  <span class="list-icons-icon">
    {% if phone.label == phone.Label.HOME %}
      <svg class="bi">
        <use href="{{ icons }}#house"></use>
      </svg>
    {% elif phone.label == phone.Label.MOBILE %}
      <svg class="bi">
        <use href="{{ icons }}#phone"></use>
      </svg>
    {% elif phone.label == phone.Label.WORK %}
      <svg class="bi">
        <use href="{{ icons }}#building"></use>
      </svg>
    {% else %}
      <svg class="bi">
        <use href="{{ icons }}#telephone"></use>
      </svg>
    {% endif %}
    {% if not phone.is_published %}
      <svg class="bi">
        <use href="{{ icons }}#eye-slash"></use>
      </svg>
    {% endif %}
  </span>

{% if request.resolver_match.url_name == 'detail' %}
  <a href="tel:{{ phone.number.as_e164 }}" class="card-link text-decoration-none">
{% endif %}
  {{ phone }}
{% if request.resolver_match.url_name == 'detail' %}
  </a>
{% endif %}
</div>
{% if members_are_related %}
  <div class="btn-group" role="group" aria-label="{% translate 'Phone number editing buttons' %}">
    <button class="btn btn-outline-secondary btn-sm"
            hx-trigger="click"
            hx-get=""
            hx-target="#phone-{{ phone.pk }}"
            aria-label="{% translate 'edit' %}">
      <svg class="bi">
        <use href="{{ icons }}#pencil-square"></use>
      </svg>
    </button>
    <a class="btn btn-outline-danger btn-sm"
       href=""
       hx-delete=""
       hx-confirm=""
       hx-target="#phone-{{ phone.pk }}"
       hx-swap="outerHTML"
       aria-label="{% translate 'delete' %}">
      <svg class="bi">
        <use href="{{ icons }}#trash"></use>
      </svg>
    </a>
  </div>
{% endif %}