trooper/members/auth/urls.py
from django.urls import path

from trooper.members.auth.views import (
    MemberLoginView,
    MemberLogoutView,
    MemberPasswordChangeView,
    MemberPasswordResetConfirmView,
    MemberPasswordResetView,
)

app_name = "auth"
urlpatterns = [
    path(
        "login/",
        MemberLoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        MemberLogoutView.as_view(),
        name="logout",
    ),
    path(
        "password/change/",
        MemberPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password/reset/",
        MemberPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password/reset/<uidb64>/<token>/",
        MemberPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

trooper/members/urls.py
from django.urls import path, register_converter

from trooper.members import views
from trooper.members.converters import FilterConverter

register_converter(FilterConverter, "filter")

app_name = "members"
urlpatterns = [
    path("", views.MemberListView.as_view(), name="list"),
    path("<filter:filter>/", views.MemberListView.as_view(), name="list_filtered"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<slug:username>/", views.MemberDetailView.as_view(), name="detail"),
    path("<slug:username>/edit/", views.MemberUpdateView.as_view(), name="update"),
    path("<slug:username>/delete/", views.MemberDeleteView.as_view(), name="delete"),
    path("<slug:username>/vcard/", views.member_vcard_view, name="vcard"),
]

trooper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path
from django.views import defaults


def ping(*args):
    return JsonResponse({"ping": "pong"})


urlpatterns = [
    # Ping test endpoint
    path("ping/", ping, name="ping"),
    # Django admin
    path("admindocs/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # Trooper
    path("", include("trooper.members.auth.urls")),
    path("address_book/", include("trooper.address_book.urls")),
    path("calendars/", include("trooper.calendars.urls")),
    path("members/", include("trooper.members.urls")),
    path("", include("trooper.website.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [
        # Debug error webpages
        path(
            "400/", defaults.bad_request, kwargs={"exception": Exception("Bad Request")}
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", defaults.server_error),
    ] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        try:
            import debug_toolbar
        except ImportError:
            pass
        else:
            urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

trooper/website/urls.py
from django.urls import path

from trooper.website import views

urlpatterns = [
    path("", views.HomePageView.as_view(), name="home_page"),
    path("css/colors.css", views.color_css, name="color_css"),
    path("about/", views.AboutPageView.as_view(), name="about_page"),
    path("contact/", views.ContactPageView.as_view(), name="contact_page"),
    path("signup/", views.SignUpPageView.as_view(), name="signup_page"),
    path("<slug:slug>/", views.PageDetailView.as_view(), name="detail"),
]

trooper/website/models.py
from pathlib import Path

from django.core.cache import cache
from django.db import models
from django.db.utils import OperationalError, ProgrammingError
from django.urls import reverse
from django.utils.html import strip_tags
from django.utils.text import Truncator, slugify
from django.utils.translation import gettext as _

from colorfield.fields import ColorField

from trooper.website.managers import ContentManager, PageQuerySet


class Configuration(models.Model):
    PRIMARY_PALETTE = [
        ("#ce1126", _("Scouting Red")),
        ("#003f87", _("Scouting Blue")),
        ("#d6cebd", _("Scouting Tan")),
        ("#515354", _("Warm Gray")),
        ("#243e2c", _("Olive")),
        ("#fdc116", _("Gold")),
        ("#ffffff", _("White")),
    ]
    SECONDARY_PALETTE = [
        ("#c54250", _("Light Red")),
        ("#860d1a", _("Dark Red")),
        ("#9ab3d5", _("Pale Blue")),
        ("#003366", _("Dark Blue")),
        ("#e9e9e4", _("Light Tan")),
        ("#ad9d7b", _("Dark Tan")),
        ("#858787", _("Pale Gray")),
        ("#232528", _("Dark Gray")),
    ]
    FULL_PALETTE = PRIMARY_PALETTE + SECONDARY_PALETTE

    name = models.CharField(_("display name"), max_length=20, default="Trooper")
    domain = models.URLField(
        _("domain name"), help_text=_("The domain name associated with this website")
    )
    description = models.CharField(
        _("description"),
        max_length=255,
        help_text=_("A brief description of this Troop"),
        blank=True,
    )
    logo = models.ImageField(
        _("logo"),
        upload_to="img",
        help_text=_("A recognizable icon to visually identify your Troop"),
        blank=True,
    )
    footer_text = models.TextField(_("footer"), blank=True)

    # Colors
    primary = ColorField(_("Primary Color"), samples=FULL_PALETTE, default="#003f87")
    secondary = ColorField(
        _("Secondary Color"), samples=FULL_PALETTE, default="#515354"
    )
    body_bg = ColorField(
        _("Body Background Color"), samples=FULL_PALETTE, default="#d6cebd"
    )
    navbar_bg = ColorField(
        _("Navbar Background Color"), samples=FULL_PALETTE, default="#243e2c"
    )

    class Meta:
        verbose_name = _("Configuration")
        verbose_name_plural = _("Configuration")

    def __str__(self):
        return self.domain

    def save(self, **kwargs):
        # Ensure only one Configuration exists
        if self.__class__.objects.exists():
            self.pk = self.__class__.objects.first().pk
        # Update the cached version
        cache.set("configuration", self)
        super().save(**kwargs)

    def delete(self, **kwargs):
        super().delete(**kwargs)
        # Delete the cached version
        cache.delete("configuration")

    @classmethod
    def current(cls):
        try:
            configuration = cache.get_or_set("configuration", cls.objects.first())
            return configuration or cls()
        except (OperationalError, ProgrammingError):
            return cls()


class Page(models.Model):
    class BuiltIn(models.TextChoices):
        HOME = "HOME", _("Home Page")
        ABOUT = "ABOUT", _("About Us")
        CONTACT = "CONTACT", _("Contact Form")
        SIGNUP = "SIGNUP", _("Sign Up Form")
        __empty__ = _("custom webpage")

    title = models.CharField(
        _("title"),
        max_length=100,
        help_text=_(
            "The title of this page. Will be shown at the top of the page, "
            "in navigation, and in the browser's title bar."
        ),
    )
    slug = models.SlugField(
        _("slug"),
        unique=True,
        blank=True,
        help_text=_(
            "The part of the page's URL that comes after the slash. Useful "
            "in providing meaningful links."
        ),
    )
    is_builtin = models.CharField(
        _("page"),
        max_length=7,
        choices=BuiltIn.choices,
        unique=True,
        blank=True,
        null=True,
        help_text=_(
            "Some pages, such as the home page, require special treatment. "
            "If this is to be one of those special pages, you can specify "
            "it here."
        ),
    )
    in_navbar = models.BooleanField(
        _("include in navigation"),
        default=True,
        help_text=_(
            "Determines whether this page should appear in the site's "
            "navigation bar."
        ),
    )
    navbar_order = models.PositiveSmallIntegerField(
        _("navigation order"),
        unique=True,
        blank=True,
        null=True,
        help_text=_(
            "Specify the order this page should appear on the site's navigation bar."
        ),
    )
    created_at = models.DateTimeField(
        _("created"),
        auto_now_add=True,
        help_text=_("The date and time this page was first added to the database."),
    )
    last_modified = models.DateTimeField(
        _("modified"),
        auto_now=True,
        help_text=_("The date and time this page was last saved to the database."),
    )

    objects = PageQuerySet.as_manager()

    class Meta:
        verbose_name = _("Page")
        verbose_name_plural = _("Pages")

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.clean()
        super().save(**kwargs)

    def clean(self):
        if self.is_builtin == self.BuiltIn.HOME:
            self.slug = ""
        if not self.slug:
            self.slug = slugify(self.title)

    def get_absolute_url(self):
        if self.is_builtin:
            return reverse(f"{self.is_builtin.lower()}_page")
        else:
            return reverse("detail", kwargs={"slug": self.slug})


class Image(models.Model):
    file = models.ImageField(_("file"), upload_to="website")
    title = models.CharField(_("title"), max_length=150, blank=True)
    description = models.TextField(_("description"), blank=True)

    class Meta:
        verbose_name = _("Image")
        verbose_name_plural = _("Images")

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.clean()
        super().save(**kwargs)

    def clean(self):
        if not self.title:
            self.title = Path(self.file.name).stem


class Content(models.Model):
    class Visibility(models.TextChoices):
        """
        Enum representing the visibility options for content.

        Attributes:
            ANONYMOUS (str): Visibility option for anonymous/guest users.
            PUBLIC (str): Visibility option for everyone.
            MEMBERS (str): Visibility option for members only.

        """

        ANONYMOUS = "ANONYMOUS", _("Anonymous/Guests")
        PUBLIC = "PUBLIC", _("Everyone")
        MEMBERS = "MEMBERS", _("Members Only")

    class GalleryVariant(models.TextChoices):
        DARK = "carousel-dark", _("Dark")
        __empty__ = _("Light")

    page = models.ForeignKey(Page, on_delete=models.CASCADE, related_name="content")
    visibility = models.CharField(
        _("visibility"),
        max_length=9,
        choices=Visibility.choices,
        default=Visibility.MEMBERS,
        help_text=_("Controls who will be allowed to view this content."),
    )
    heading = models.CharField(_("heading"), max_length=100, blank=True)
    bookmark = models.SlugField(
        _("bookmark"),
        blank=True,
        help_text=_("Can be used to link directly to this content block on a webpage."),
    )

    body = models.TextField(
        _("body"), help_text=_("The main body of this content block")
    )
    images = models.ManyToManyField(Image, related_name="content", blank=True)
    gallery_controls = models.CharField(
        _("gallery controls"),
        max_length=13,
        choices=GalleryVariant.choices,
        blank=True,
        help_text=_(
            "Choose whether the controls, indicators, and captions are "
            "white or dark. Light controls work best when the images in "
            "the gallery are darker and dark controls appear better "
            "over light colors."
        ),
    )

    objects = ContentManager()

    class Meta:
        order_with_respect_to = "page"
        verbose_name = _("Content Block")
        verbose_name_plural = _("Content Blocks")

    def __str__(self):
        description = self.heading or Truncator(strip_tags(self.body)).words(15)
        return _("%s: %s") % (self.page, description)

trooper/website/views.py
import logging

from django.contrib.staticfiles import finders
from django.http import FileResponse, Http404
from django.shortcuts import render
from django.utils.translation import gettext as _
from django.views.decorators.cache import cache_control
from django.views.decorators.http import require_GET
from django.views.generic import DetailView, TemplateView

from trooper.website.models import Page

logger = logging.getLogger(__name__)


@require_GET
@cache_control(max_age=60 * 60 * 24, immutable=True, public=True)
def favicon(request):
    file = finders.find("favicon.ico")
    return FileResponse(open(file, "rb"))


@require_GET
@cache_control(max_age=60 * 68 * 24, immutable=True, public=True)
def color_css(request):
    return render(request, "website/css/colors.txt", content_type="text/css")


class HomePageView(TemplateView):
    template_name = "website/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            page = Page.objects.get(is_builtin=Page.BuiltIn.HOME)
        except Page.DoesNotExist:
            page = Page()
            page.title = _("Home")
            logger.info(
                _("Home page was requested but does not exist in the database!")
            )

        context["page"] = page
        return context


class AboutPageView(TemplateView):
    template_name = "website/about.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["page"] = Page.objects.get(is_builtin=Page.BuiltIn.ABOUT)
            return context
        except Page.DoesNotExist as e:
            raise Http404 from e


class ContactPageView(TemplateView):
    template_name = "website/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["page"] = Page.objects.get(is_builtin=Page.BuiltIn.CONTACT)
            return context
        except Page.DoesNotExist as e:
            raise Http404 from e


class SignUpPageView(TemplateView):
    template_name = "website/signup.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["page"] = Page.objects.get(is_builtin=Page.BuiltIn.SIGNUP)
            return context
        except Page.DoesNotExist as e:
            raise Http404 from e


class PageDetailView(DetailView):
    model = Page
    template_name = "website/detail.html"

    def get_queryset(self):
        return super().get_queryset().with_visible_content_for(self.request.user)

trooper/website/templates/website/partials/content.html
<section class="card mb-5 shadow-sm"{% if content.bookmark %} id="{{ content.bookmark }}{% endif %}">
  {% if content.images.count > 1 %}
    {% include 'website/partials/gallery.html' %}
  {% elif content.images.exists %}
    {% with image=content.images.first %}
      <figure class="figure">
        <img src="{{ image.file.url }}" class="figure-img card-img-top" alt="{{ image.title }}">
        {% if image.description %}
          <figcaption class="figure-caption px-lg-5 px-md-4 px-3">{{ image.description|linebreaks }}</figcaption>
        {% endif %}
      </figure>
    {% endwith %}
  {% endif %}
  <div class="card-body p-md-4 p-lg-5">
    {% if content.heading %}
      <h2 class="card-title mb-5">{{ content.heading }}</h2>
    {% endif %}
    <div class="card-text">{{ content.body|linebreaks|urlize }}</div>
  </div>
</section>

trooper/website/templates/website/partials/gallery.html
{% load i18n static %}
<div id="{{ content.bookmark }}-gallery" class="carousel slide {{ content.gallery_controls }}" data-bs-ride="false">
  <nav role="tablist" class="carousel-indicators dot-indicators">
    {% for image in content.images.all %}
      <button type="button"
              role="tab"
              data-bs-target="#{{ content.bookmark }}-gallery"
              data-bs-slide-to="{{ forloop.counter0 }}"
        {% if forloop.first %}
              class="active"
              aria-current="true"
        {% endif %}
              aria-label="{{ image.title }}"
      ></button>
    {% endfor %}
  </nav>
  <div class="carousel-inner rounded-top">
    {% for image in content.images.all %}
      <figure class="figure carousel-item{% if forloop.first %} active{% endif %}">
        <img src="{{ image.file.url }}" class="figure-img d-block w-100" alt="{{ image.title }}">
        {% if image.description %}
          <figcaption class="figure-caption px-lg-5 px-md-4 px-3 mb-4">{{ image.description|linebreaks }}</figcaption>
        {% endif %}
      </figure>
    {% endfor %}
  </div>
  <button class="carousel-control-prev"
          type="button"
          data-bs-target="#{{ content.bookmark }}-gallery"
          data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">{% translate 'Previous' %}</span>
  </button>
  <button class="carousel-control-next"
          type="button"
          data-bs-target="#{{ content.bookmark }}-gallery"
          data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">{% translate 'Next' %}</span>
  </button>
</div>

trooper/website/templates/website/partials/navbar.html
{% load i18n static thumbnail %}{% static 'img/bootstrap-icons.svg' as icons %}
<!-- Begin site navigation -->
<nav class="navbar navbar-expand-lg navbar-dark" id="site-navbar">
  <div class="container">
    <button class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarContent"
            aria-controls="navbarContent"
            aria-expanded="false"
            aria-label="{% translate 'Toggle navigation' %}"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    {% thumbnail website.logo "x36" format="PNG" as img %}
      <a class="navbar-brand" href="{% url 'home_page' %}">
        <img src="{{ img.url }}"
             srcset="{{ img.url }} 1x, {{ img.url|resolution:'2x' }} 2x"
             alt="{{ website.name }}"
             width="{{ img.width }}"
             height="{{ img.height }}"
        >
      </a>
    {% empty %}
      <a class="navbar-brand" href="{% url 'home_page' %}">{{ website.name }}</a>
    {% endthumbnail %}
    <div class="d-lg-none navbar-toggler-offset"></div>
    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav me-auto">
        {% for page in navbar.links %}
          <li class="nav-item">
            <a href="{{ page.url }}"
              {% if page.is_current %}
               class="nav-link active"
               aria-current="page"
              {% else %}
               class="nav-link"
              {% endif %}
            >
              {{ page.title }}
            </a>
          </li>
        {% endfor %}
      </ul>
      {% if request.resolver_match.app_name != "auth" %}
        <ul class="navbar-nav" id="user-menu">
          <li class="nav-item dropdown">
            <a href="#"
               class="nav-link dropdown-toggle{% if request.user.is_authenticated %} active{% endif %}"
               id="user-menu-toggle"
               role="button"
               data-bs-toggle="dropdown"
               aria-expanded="false"
            >
              {% thumbnail request.user.photo "32x32" crop="center" format="PNG" as img %}
                <img src="{{ img.url }}"
                     srcset="{{ img.url }} 1x, {{ img.url|resolution:'2x' }} 2x"
                     class="rounded-circle"
                     alt="{{ request.user }}"
                     width="{{ img.width }}"
                     height="{{ img.height }}"
                >
              {% empty %}
                <svg class="bi fs-5">
                  <use href="{{ icons }}#person-circle"></use>
                </svg>
              {% endthumbnail %}
              <span class="visually-hidden">{% translate 'User Menu' %}</span>
            </a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="user-menu-toggle">
              {% if request.user.is_authenticated %}
                <li>
                  <a href="{{ request.user.get_absolute_url }}" class="dropdown-item">
                    <svg class="bi">
                      <use href="{{ icons }}#person-fill"></use>
                    </svg>
                    <span>{% translate 'My profile' %}</span>
                  </a>
                </li>
                <li>
                  <a href="{% url 'auth:password_change' %}" class="dropdown-item">
                    <svg class="bi">
                      <use href="{{ icons }}#key-fill"></use>
                    </svg>
                    <span>{% translate 'Update password' %}</span>
                  </a>
                </li>
                {% if request.user.is_staff %}
                  <li>
                    <a href="{% url 'admin:index' %}" class="dropdown-item">
                      <svg class="bi">
                        <use href="{{ icons }}#gear-fill"></use>
                      </svg>
                      <span>{% translate 'Administration' %}</span>
                    </a>
                  </li>
                {% endif %}
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li>
                  <form action="{% url 'auth:logout' %}" method="post" class="dropdown-item" id="navbar-logout">
                    <button type="submit" class="text-danger">
                      <svg class="bi">
                        <use href="{{ icons }}#box-arrow-right"></use>
                      </svg>
                      <span>{% translate 'Logout' %}</span>
                    </button>
                    {% csrf_token %}
                  </form>
                </li>
              {% else %}
                <form action="{% url 'auth:login' %}" method="post" class="login-form" id="navbar-signin">
                  <fieldset>
                    <div class="form-floating">
                      <input type="text"
                             name="username"
                             autocomplete="username"
                             class="form-control"
                             id="id_username"
                             placeholder="{% translate 'name@example.com' %}"
                             autocapitalize="none"
                             maxlength="150"
                             required
                      >
                      <label for="id_username">{% translate 'Username / Email' %}</label>
                    </div>
                    <div class="form-floating">
                      <input type="password"
                             name="password"
                             autocomplete="current-password"
                             required
                             class="form-control"
                             id="id_password"
                             placeholder="{% translate 'password' %}"
                      >
                      <label for="id_password">{% translate 'Password' %}</label>
                    </div>
                  </fieldset>
                  {% csrf_token %}
                  <input type="hidden" name="next" value="{{ request.path }}">
                  <button type="submit" class="btn btn-primary w-100">{% translate 'Sign in' %}</button>
                </form>
                <div class="dropdown-divider"></div>
                <a href="{% url 'auth:password_reset' %}" class="dropdown-item px-4">
                  <small>{% translate 'Forgot your password?' %}</small>
                </a>
                <a href="{% url 'members:signup' %}" class="dropdown-item px-4">
                  <small>{% translate 'Need an account? Join us!' %}</small>
                </a>
              {% endif %}
            </ul>
          </li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

trooper/website/templates/website/partials/sidebar.html
{% if page.visible_content|length > 1 %}
  <aside class="col-lg-3 order-lg-1">
    <nav class="nav nav-pills flex-lg-column sticky-aside" id="link-sidebar">
        <a href="#" class="nav-link active">
          <strong>{{ page.title }}</strong>
        </a>
      <nav class="nav nav-pills flex-column">
        {% for content in page.visible_content %}
          {% if content.bookmark %}
              <a href="#{{ content.bookmark }}"
                 class="nav-link ps-4 my-1"
              >
                {{ content.heading }}
              </a>
          {% endif %}
        {% endfor %}
      </nav>
    </nav>
  </aside>
{% endif %}