trooper/members/auth/urls.py
from django.urls import path

from trooper.members.auth.views import (
    MemberLoginView,
    MemberLogoutView,
    MemberPasswordChangeView,
    MemberPasswordResetConfirmView,
    MemberPasswordResetView,
)

app_name = "auth"
urlpatterns = [
    path(
        "login/",
        MemberLoginView.as_view(),
        name="login",
    ),
    path(
        "logout/",
        MemberLogoutView.as_view(),
        name="logout",
    ),
    path(
        "password/change/",
        MemberPasswordChangeView.as_view(),
        name="password_change",
    ),
    path(
        "password/reset/",
        MemberPasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "password/reset/<uidb64>/<token>/",
        MemberPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

trooper/members/urls.py
from django.urls import path, register_converter

from trooper.members import views
from trooper.members.converters import FilterConverter

register_converter(FilterConverter, "filter")

app_name = "members"
urlpatterns = [
    path("", views.MemberListView.as_view(), name="list"),
    path("<filter:filter>/", views.MemberListView.as_view(), name="list_filtered"),
    path("signup/", views.SignupView.as_view(), name="signup"),
    path("<slug:username>/", views.MemberDetailView.as_view(), name="detail"),
    path("<slug:username>/edit/", views.MemberUpdateView.as_view(), name="update"),
    path("<slug:username>/delete/", views.MemberDeleteView.as_view(), name="delete"),
    path("<slug:username>/vcard/", views.member_vcard_view, name="vcard"),
]

trooper/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.http import JsonResponse
from django.urls import include, path
from django.views import defaults


def ping(*args):
    return JsonResponse({"ping": "pong"})


urlpatterns = [
    # Ping test endpoint
    path("ping/", ping, name="ping"),
    # Django admin
    path("admindocs/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    # Trooper
    path("", include("trooper.members.auth.urls")),
    path("address_book/", include("trooper.address_book.urls")),
    path("calendars/", include("trooper.calendars.urls")),
    path("members/", include("trooper.members.urls")),
    path("", include("trooper.website.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns = [
        # Debug error webpages
        path(
            "400/", defaults.bad_request, kwargs={"exception": Exception("Bad Request")}
        ),
        path(
            "403/",
            defaults.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            defaults.page_not_found,
            kwargs={"exception": Exception("Page Not Found")},
        ),
        path("500/", defaults.server_error),
    ] + urlpatterns

    if "debug_toolbar" in settings.INSTALLED_APPS:
        try:
            import debug_toolbar
        except ImportError:
            pass
        else:
            urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

trooper/members/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.validators import ASCIIUsernameValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.utils.translation import gettext as _

from trooper.address_book.models import Address as BaseAddress
from trooper.address_book.models import EmailAddress as BaseEmailAddress
from trooper.address_book.models import EmailAddressManager
from trooper.address_book.models import PhoneNumber as BasePhoneNumber
from trooper.address_book.models import PhoneNumberManager
from trooper.members.managers import (
    FamilyQuerySet,
    MemberManager,
    PublishedQuerySet,
    PublishedSubscribedQuerySet,
)
from trooper.members.utils import calculate_age, get_member_photo_upload_to
from trooper.members.validators import date_of_birth_validator, date_of_death_validator


class Member(AbstractUser):
    class Gender(models.TextChoices):
        MALE = "M", _("Male")
        FEMALE = "F", _("Female")
        OTHER = "O", _("Other")

    username_validator = ASCIIUsernameValidator()

    uuid = models.UUIDField(
        _("UUID"), primary_key=True, editable=False, default=uuid.uuid4
    )
    username = models.CharField(
        _("username"),
        max_length=150,
        unique=True,
        help_text=_(
            "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only."
        ),
        validators=[username_validator],
        error_messages={
            "unique": _("A member with that username already exists."),
        },
    )
    first_name = models.CharField(_("first name"), max_length=100)
    middle_name = models.CharField(_("middle name"), max_length=100, blank=True)
    last_name = models.CharField(_("last name"), max_length=100)
    suffix = models.CharField(_("suffix"), max_length=10, blank=True)
    nickname = models.CharField(
        _("nickname"),
        max_length=100,
        blank=True,
        help_text=_("The name this member prefers to be known by."),
    )
    photo = models.ImageField(
        _("profile picture"),
        upload_to=get_member_photo_upload_to,
        blank=True,
        null=True,
        help_text=_(
            "A profile photo is used in the site directory to assist members match "
            "names with faces. A good photo is one taken from the shoulders up "
            "with the face clearly visible. Photos are only available to active "
            "members and never shared outside of the Troop."
        ),
    )
    gender = models.CharField(_("gender"), max_length=1, choices=Gender.choices)
    date_of_birth = models.DateField(
        _("date of birth"), validators=[date_of_birth_validator]
    )
    date_of_death = models.DateField(
        _("date of death"), validators=[date_of_death_validator], blank=True, null=True
    )

    objects = MemberManager()

    REQUIRED_FIELDS = ["first_name", "last_name", "gender", "date_of_birth"]

    class Meta:
        ordering = ["last_name", "nickname", "first_name"]
        verbose_name = _("Member")
        verbose_name_plural = _("Members")

    def __str__(self):
        return self.get_full_name()

    def save(self, *args, **kwargs):
        """
        Ensure all members get a username based on their preferred
        full name.
        """
        if not self.username:
            self.username = slugify(self.get_full_name())
        super().save(*args, **kwargs)

    def clean(self):
        """
        Override AbstractUser clean() method that tries to clean
        the no-existent email field.
        """
        pass

    def get_short_name(self):
        """
        Return either the short name for the Member.
        """
        return self.nickname or self.first_name

    def get_full_name(self):
        """
        Return the full name for the Member.
        """
        full_name = f"{self.get_short_name()} {self.last_name} {self.suffix}"
        return full_name.strip()

    def get_absolute_url(self):
        """
        Return the member detail page for the Member.
        """
        return reverse("members:detail", kwargs={"username": self.username})

    def get_family_members(self, families=None, filters=None):
        if families is None:
            families = self.families.all()

        members = self._meta.model.objects.none()
        for family in families:
            family_members = self._meta.model.objects.filter(
                families=family, **filters
            ).exclude(pk=self.pk)
            members = members.union(family_members)
        return members

    def adult_families(self):
        """Returns a Family QuerySet where member's role is `PARENT`."""
        return self.families.filter(
            family_member__role=self.families.through.Role.PARENT
        )

    def childhood_families(self):
        """Returns a Family QuerySet where member's role is `CHILD`."""
        return self.families.filter(
            family_member__role=self.families.through.Role.CHILD
        )

    @property
    def children(self):
        """Returns a queryset containing member's children."""
        return self.get_family_members(
            families=self.adult_families(),
            filters={"family_member__role": self.families.through.Role.CHILD},
        )

    @property
    def parents(self):
        """Returns a queryset containing member's parents."""
        return self.get_family_members(
            families=self.childhood_families(),
            filters={"family_member__role": self.families.through.Role.PARENT},
        )

    @property
    def partners(self):
        """Returns a queryset containing member's spouses or partners."""
        return self.get_family_members(
            families=self.adult_families(),
            filters={"family_member__role": self.families.through.Role.PARENT},
        )

    @property
    def siblings(self):
        """Returns a queryset containing member's siblings."""
        return self.get_family_members(
            families=self.childhood_families(),
            filters={"family_member__role": self.families.through.Role.CHILD},
        )

    def is_related_to(self, member):
        """Returns a boolean of whether two members share a family."""
        if member == self:
            return True
        family_model = self.families.model
        return family_model.objects.filter(members=self).filter(members=member).exists()

    @property
    def email(self):
        """Returns an email address if available."""
        return self.email_addresses.first() or ""

    @classmethod
    def normalize_username(cls, username):
        """Ensure username is conformant and lower case."""
        return super().normalize_username(username.lower())

    @property
    def short_name(self):
        return self.get_short_name()

    @property
    def age(self):
        """Calculate the member's age."""
        return calculate_age(self.date_of_birth, on_date=self.date_of_death)

    @classmethod
    def adult_choices(cls):
        """
        Provides a queryset filter that can be used in other models'
        `ForeignKey` fields implementing `limit_choices_to`.

        Returns a filter including only adult members.
        """
        return {"pk__in": cls.objects.adults()}

    @classmethod
    def youth_choices(cls):
        """
        Provides a queryset filter that can be used in other models'
        `ForeignKey` fields implementing `limit_choices_to`.

        Returns a filter including only youth members.
        """
        return {"pk__in": cls.objects.youths()}


class Family(models.Model):
    members = models.ManyToManyField(
        Member, through="FamilyMember", related_name="families"
    )

    objects = FamilyQuerySet.as_manager()

    class Meta:
        verbose_name = _("Family")
        verbose_name_plural = _("Families")

    def __str__(self):
        if not self.members.count():
            return _("new family")
        names = (
            self.members.exclude(last_name="")
            .order_by("last_name")
            .values_list("last_name", flat=True)
        )
        return _("%s Family") % "/".join(set(names)) if names else _("Unknown Family")


class FamilyMember(models.Model):
    class Role(models.TextChoices):
        PARENT = "P", _("Parent")
        CHILD = "C", _("Child")

    family = models.ForeignKey(
        Family,
        on_delete=models.CASCADE,
        related_name="family_members",
        related_query_name="family_member",
    )
    member = models.ForeignKey(
        Member,
        on_delete=models.CASCADE,
        related_name="family_members",
        related_query_name="family_member",
    )
    role = models.CharField(_("role"), max_length=1, choices=Role.choices)

    class Meta:
        db_table = "members_family_member"
        verbose_name = _("Family Member")
        verbose_name_plural = _("Family Members")

    def __str__(self):
        return self.member.__str__()


class Address(BaseAddress):
    class Label(models.TextChoices):
        HOME = "HOME", _("Home")
        WORK = "WORK", _("Work")
        SCHOOL = "SCHOOL", _("School")
        PO_BOX = "POB", _("P.O. Box")

    member = models.ForeignKey(
        Member, on_delete=models.CASCADE, related_name="addresses"
    )
    label = models.CharField(
        _("label"), max_length=6, choices=Label.choices, blank=True
    )
    is_published = models.BooleanField(
        _("published in directory"),
        default=True,
        help_text=_("Allow others to see this address in the member directory."),
    )

    objects = PublishedQuerySet.as_manager()


class EmailAddress(BaseEmailAddress):
    class Label(models.TextChoices):
        HOME = "HOME", _("Home")
        SCHOOL = "SCHOOL", _("School")
        WORK = "WORK", _("Work")

    member = models.ForeignKey(
        Member,
        on_delete=models.CASCADE,
        related_name="email_addresses",

trooper/members/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from trooper.members.forms import MemberChangeForm, MemberSignupForm
from trooper.members.models import Member
from trooper.members.utils import member_vcard

logger = logging.getLogger(__name__)


class SignupView(SuccessMessageMixin, CreateView):
    form_class = MemberSignupForm
    template_name = "members/signup.html"
    success_message = _(
        "An account has been created for <strong>%(first_name)s</strong>."
    )
    success_url = reverse_lazy("auth:login")


class MemberListView(LoginRequiredMixin, ListView):
    model = Member
    template_name = "members/member_list.html"
    paginate_by = 10

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        if "filter" in self.kwargs:
            context["filter"] = self.kwargs["filter"]
        if self.request.GET.get("q"):
            context["q"] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        # qs = qs.with_published_contact_info()
        if "filter" in self.kwargs:
            filter_to = self.kwargs["filter"]
            if filter_to in self.model.objects.FILTERS_AVAILABLE:
                qs_filter = getattr(qs, filter_to)
                qs = qs_filter()
        if query := self.request.GET.get("q", default=""):
            qs = qs.search(query=query)
        return qs

    def get_template_names(self):
        if self.request.htmx:
            if self.request.GET.get("page"):
                return "members/partials/member_list_entries.html"
            return "members/partials/member_list.html"
        return self.template_name


class MemberDetailView(LoginRequiredMixin, UpdateView):
    model = Member
    form_class = MemberChangeForm
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "members/member_detail.html"

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     return queryset.with_published_contact_info()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["object"].is_related = self.object.is_related_to(self.request.user)
        return context


class MemberUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Member
    form_class = MemberChangeForm
    slug_field = "username"
    slug_url_kwarg = "username"
    success_message = _(
        "Member <strong>%(member)s</strong> has been successfully updated."
    )


class MemberDeleteView(LoginRequiredMixin, DeleteView):
    model = Member
    slug_field = "username"
    slug_url_kwarg = "username"
    success_url = reverse_lazy("members:list")

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        success_message = (
            _(
                "Member <strong>%s</strong> has been permanently removed "
                "from the database."
            )
            % self.object
        )
        self.object.delete()
        messages.warning(request, success_message)
        logger.info(_("%s was deleted by %s") % (self.object, request.user))
        return HttpResponseRedirect(success_url)


def member_vcard_view(request, username):
    member = get_object_or_404(Member, username=username)
    card = member_vcard(member)
    filename = f"{member.get_full_name()}.vcf"
    response = HttpResponse(card.serialize(), content_type="text/x-vcard")
    response["Content-Disposition"] = f"attachment; filename={filename}"
    return response

trooper/members/templates/members/partials/member_detail.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
<div class="card mb-3">
  <div class="card-body">
    <div class="row mb-5 mb-lg-0">
      <div class="col-lg">
        {% include 'members/partials/member_list_entry_profile_picture.html' %}
        <div class="d-flex flex-column">
          <h2 class="card-title">
            {% if request.path == member.get_absolute_url %}
              {{ member.get_full_name }}
              <a href="{% url 'members:vcard' username=member.username %}"
                 data-bs-toggle="tooltip"
                 title="{% translate 'Add to your contacts' %}">
                <svg class="bi">
                  <use href="{{ icons }}#person-vcard"></use>
                </svg>
              </a>
            {% else %}
              <a class="stretched-link text-decoration-none"
                 href="{{ member.get_absolute_url }}">{{ member.get_full_name }}</a>
            {% endif %}
          </h2>
          <h3 class="card-subtitle fs-5 text-muted">{{ member.username }}</h3>
          {% if tag %}
            <p class="card-text"><span class="badge rounded-pill text-bg-secondary">{{ tag }}</span></p>{% endif %}
          {% if member.age < 18 %}
            <p class="card-text">
              <svg class="bi">
                <use href="{{ icons }}#gift"></use>
              </svg>
              {{ member.date_of_birth }}
            </p>
          {% endif %}
        </div>
      </div>
      {% if not summary %}
        <div class="col-lg-5">
          <address class="card-text">
            {% include 'address_book/partials/address_list.html' with address_list=member.addresses.all %}
            {% include 'address_book/partials/email_address_list.html' with email_addresses=member.email_addresses.all %}
            {% include 'address_book/partials/phone_number_list.html' with phone_numbers=member.phone_numbers.all %}
          </address>
        </div>
      {% endif %}
    </div>
  </div>
</div>

trooper/members/templates/members/partials/member_list.html
{% load i18n %}
<div class="card shadow-sm" id="member-list">
  <div class="card-header">
    {% include 'members/partials/member_list_tabs.html' %}
  </div>
  <div class="card-body">
    <div class="list-group list-group-flush" hx-indicator=".htmx-indicator">
      {% include 'members/partials/member_list_entries.html' %}
    </div>
    <div class="htmx-indicator" id="members-indicator">
      <div class="spinner-border text-primary m-3 p-3" role="status"></div>
    </div>
  </div>
</div>

trooper/members/templates/members/partials/member_list_entries.html
{% load i18n %}
{% for member in member_list %}
  {% include 'members/partials/member_list_entry.html' %}
{% empty %}
  <div class="text-center py-5">
    {% translate 'No Members Found' %}
  </div>
{% endfor %}

trooper/members/templates/members/partials/member_list_entry.html
<a class="list-group-item list-group-item-action d-flex p-4"
   href="{{ member.get_absolute_url }}"
  {% if forloop.last and page_obj.has_next %}
   hx-get="?page={{ page_obj.next_page_number }}"
   hx-trigger="revealed"
   hx-swap="afterend"
  {% endif %}
>
  {% include 'members/partials/member_list_entry_profile_picture.html' %}
  <div>
    <h2>{{ member.get_full_name }}</h2>
    <p><span class="badge rounded-pill text-bg-secondary">{{ member.age }}</span></p>
  </div>
</a>
  {% if member.published_addresses %}
    {% include 'address_book/partials/address_list.html' with address_list=member.published_addresses links=False %}
  {% endif %}
  {% if member.published_email_addresses %}
    {% include 'address_book/partials/email_address_list.html' with email_addresses=member.published_email_addresses links=False %}
  {% endif %}
  {% if member.published_phone_numbers %}
    {% include 'address_book/partials/phone_number_list.html' with phone_numbers=member.published_phone_numbers links=False %}
  {% endif %}

trooper/members/templates/members/partials/member_list_entry_profile_picture.html
{% load i18n static thumbnail %}
{% blocktranslate with short_name=member.short_name asvar alt_text %}{{ short_name }}'s profile picture{% endblocktranslate %}
<img alt="{{ alt_text }}"
  {% thumbnail member.photo "x80" format="PNG" as img %}
     src="{{ img.url }}"
     srcset="{{ img.url }} 1x, {{ img.url|resolution:'2x' }} 2x"
  {% empty %}
     {# Use Generic icons if the Member doesn't have a profile picture. #}
    {% if member.age < 18 %}
     src="{% static 'img/avatar_cub_80x80.png' %}"
    {% elif member.gender == member.Gender.MALE %}
     src="{% static 'img/avatar_man_80x80.png' %}"
    {% elif member.gender == member.Gender.FEMALE %}
     src="{% static 'img/avatar_woman_80x80.png' %}"
    {% else %}
     src="{% static 'img/avatar_generic_80x80.png' %}"
    {% endif %}
  {% endthumbnail %}
     width="80"
     height="80"
     class="img-fluid rounded-circle me-3"
>

trooper/members/templates/members/partials/member_list_tabs.html
{% load i18n %}
<nav class="nav nav-tabs card-header-tabs">
  <a href="{% url 'members:list' %}{% if q %}?q={{ q }}{% endif %}"
    {% if not filter %}
     class="nav-link active"
     aria-current="true"
    {% else %}
     class="nav-link"
    {% endif %}
     hx-get="{% url 'members:list' %}{% if q %}?q={{ q }}{% endif %}"
     hx-push-url="true"
     hx-swap="outerHTML"
     hx-target="#member-list"
     hx-indicator="#members-indicator"
  >
    {% translate 'All Members' %}
  </a>
  <a href="{% url 'members:list_filtered' filter='adults' %}{% if q %}?q={{ q }}{% endif %}"
    {% if filter == "adults" %}
     class="nav-link active"
     aria-current="true"
    {% else %}
     class="nav-link"
    {% endif %}
     hx-get="{% url 'members:list_filtered' filter='adults' %}{% if q %}?q={{ q }}{% endif %}"
     hx-push-url="true"
     hx-swap="outerHTML"
     hx-target="#member-list"
     hx-indicator="#members-indicator"
  >
    {% translate 'Adults' %}
  </a>
  <a href="{% url 'members:list_filtered' filter='youths' %}{% if q %}?q={{ q }}{% endif %}"
    {% if filter == "youths" %}
     class="nav-link active"
     aria-current="true"
    {% else %}
     class="nav-link"
    {% endif %}
     hx-get="{% url 'members:list_filtered' filter='youths' %}{% if q %}?q={{ q }}{% endif %}"
     hx-push-url="true"
     hx-swap="outerHTML"
     hx-target="#member-list"
     hx-indicator="#members-indicator"
  >
    {% translate 'Youths' %}
  </a>
</nav>

trooper/members/templates/members/partials/members_header.html
{% load i18n %}
<div class="d-flex align-items-center justify-content-between mb-5" id="page-header">
  <h1><a href="{% url 'members:list' %}" class="text-decoration-none">{% translate 'Members' %}</a></h1>
  {% if show_search %}{% include  'members/partials/search_form.html' %}{% endif %}
</div>

trooper/members/templates/members/partials/search_form.html
{% load i18n static %}{% static 'img/bootstrap-icons.svg' as icons %}
{% translate "Search" as search_text %}
<form action="." method="get">
  <div class="input-group">
    <input class="form-control"
           type="search"
           name="q"
           id="id_query"
           placeholder="{{ search_text }}"
           aria-label="{{ search_text }}"
           value="{{ q }}"
           hx-get="."
           hx-swap="outerHTML"
           hx-target="#member-list"
           hx-trigger="keyup changed delay:500ms, search"
           hx-indicator="#members-indicator"
    >
    <button type="submit" class="btn btn-success" aria-label="{{ search_text }}">
      <svg class="bi">
        <use href="{{ icons }}#search"></use>
      </svg>
    </button>
  </div>
</form>